#!/bin/bash

URL="https://www.math.uni.lodz.pl/~arogow/2022-23/md/"
STORED_FILE="prev.html"
TEMP_FILE="next.html"

while true; do

	curl --silent "$URL" >"$TEMP_FILE"
	if [ ! -f "$STORED_FILE" ]; then
		cp "$TEMP_FILE" "$STORED_FILE"
	fi

	diff -q "$TEMP_FILE" "$STORED_FILE" >/dev/null
	if [ $? -ne 0 ]; then
		echo "rogow dodaje kolokwia!"
		cp "$TEMP_FILE" "$STORED_FILE"
	else
		echo "brak zmian"
	fi
	sleep 0.5
done
